### PR TITLE
Fix prepaid amount in importer

### LINKED ISSUE #475: Example invoice coud not be parsed
While implementing in Jes, I used the [example invoices from OpenXRechnungToolbox](https://github.com/jcthiele/OpenXRechnungToolbox/tree/master/exampleInvoices/XRechnung_v2.2.0) for my tests. Most of them work well, but I got a ParseException for 04.01a-INVOICE_ubl.xml.

Could you check what's wrong?

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #475

### CODE REVIEW

File: library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java [hunk 1]
```diff
@@ -39,8 +39,8 @@ protected BigDecimal getTotalPrepaid() {
 	}
 
 	/***
-	 * the invoice total with VAT, corrected by prepaid amount, allowances and
-	 * charges
+	 * the invoice total with VAT, allowances and
+	 * charges, WITHOUT considering prepaid amount
```
Comment (J-N-K) [inline library/src/main/java/org/mustangproject/ZUGFeRD/TransactionCalculator.java:43]: This was wrong JavaDoc. The prepaid amount is not considered when calculating the grand total (and this is the expected behavior by other methods).
